### ISSUE TITLE
build ogg failure with ios7

### ISSUE THREAD

**Issue by takanoter** [iosdevzone/IDZPrecompiledOgg#1]
hi, i got failure when building ogg, and here's configure.log:

Apple LLVM version 5.1 (clang-503.0.38) (based on LLVM 3.4svn)
Target: x86_64-apple-darwin12.5.0
Thread model: posix
configure:3377: $? = 0
configure:3366: gcc -V >&5
clang: error: argument to '-V' is missing (expected 1 value)
clang: error: no input files
configure:3377: $? = 1
configure:3366: gcc -qversion >&5
clang: error: unknown argument: '-qversion' [-Wunused-command-line-argument-hard-error-in-future]
clang: note: this will be a hard error (cannot be downgraded to a warning) in the future
clang: error: no input files
configure:3377: $? = 1
configure:3397: checking whether the C compiler works
configure:3419: gcc -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.0.sdk -arch armv7 -miphoneos-version-min=7.0  -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.0.sdk -arch armv7 -miphoneos-version-min=7.0 conftest.c  >&5
clang: warning: no such sysroot directory: '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.0.sdk'
ld: library not found for -lSystem
clang: error: linker command failed with exit code 1 (use -v to see invocation)
configure:3423: $? = 1
configure:3461: result: no

is there any way i can solve it? thanks:)

**Comment by iosdevzone** [comment]
Hi takanoter,

It looks like there are two problems.
1) You are not setting the correct SDK
2) Something in clang 5.1 is incompatible with the Gnu configure script.

The easiest solution to both problems is simply to use the precompiled libraries from this repository. 

However if you want to try and solve the problem, I suggest the following.

Set the version in `libogg_build.bash` to match your SDK version (i.e. change 7.0 -> 7.1). (I see now I should have used a variable for that. It's a bit ugly.) Then retry your build. If the problem with `-V` and other command line arguments stops this build then your best option is to download Xcode 5.0 and use it to build the library.

Let me know which solution worked for you,
idz

**Comment by iosdevzone** [comment]
Closing this due to lack of response
