### ISSUE TITLE
Inclusion of new bitcode format

### ISSUE THREAD

**Issue by Andos** [iosdevzone/IDZPrecompiledOgg#3]
The new Xcode will now build a using a new bitcode format and calls the new target "OSX".
This gives linker errors when linking with this framework in the new XCode:

ld: building for OSX, but linking in object file built for iOS, for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by iosdevzone** [comment]
I'll take a look at it and get back to you. Sorry for the delay in replying.

**Comment by iosdevzone** [comment]
Hi Andos,
I just created  and linked a test app using Xcode 7.0 (7A220) with bitcode enabled and was able to link successfully, run it on the simulator and run it on a device. 
Is your project on GitHub somewhere? I can take a look and see if I can help you out. If not, if you want to create a minimal reproducible test case and send it to me I am more than happy to take a look. 
Normally, the error you are seeing indicates that you are trying to link an iOS framework (which this one is) with an 'OS X' (i.e. for the Mac) target. I haven't played too much the bitcode stuff so maybe I am missing something.
Anyway let me know and I'll do my best to help you out.
idz

**Comment by zwang** [comment]
I had the problem of uploading the app archive to app store. It can not pass the validation phase. And I googled around, found the error is caused by bitcode enabled, but the framework does not support bitcode. So it failed. Right after I disable bit code in xcode for that project, the issue is fixed.

**Comment by zwang** [comment]
Here is the detail of error information when I try to run it on my development device with BitCode enabled. I am using XCode 7.1 (7B91b) with my device running iOS 8.4.1. And my os is El Capitan. Thanks. 

ld: '/Users/zhao/workspace/Pla/Pla/Libs/IDZAudioPlayer/Frameworks/IDZPrecompiledVorbis/Vorbis.framework/Vorbis(vorbisfile.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by iosdevzone** [comment]
@zwang thanks for the additional information. I will try to deal with this in the next day or two.

**Comment by iosdevzone** [comment]
Release 2.0.0 contains embedded bitcode.
