### ISSUE TITLE
Can I rebuild libogg as a dynamic framework with XCode if I only care about iOS 8.0 +

### ISSUE THREAD

**Issue by zwang** [iosdevzone/IDZPrecompiledOgg#5]
Thank you for your help! :+1:

**Comment by iosdevzone** [comment]
Yes you can. For `libogg` this may not be too hard (you will just have to figure out all the correct compiler flags). For some other libraries this can be quite complex.

**Comment by zwang** [comment]
I see. Thanks for the insights. It's probably not worthing it for now then since I have no idea of those compiler flags.

I actually just need a player. I am using your IDZPlayer. But having some memory problem. I was thinking to use a framework to build a player that can be used with Carthage and/or cocoaPods. I think I should just focusing on improving the player and maybe contribute back to your IDZAudioPlayer demo project. 

Appreciate your help and insights.
